#!/bin/bash
# =============================================================
#  build_cec17.sh
#
#  Compiles the CEC17 pure-C files into cec17.so
#  Works on macOS and Linux — no Windows headers involved.
#
#  Files used:
#      cec17_test_func.c   ← the 29 benchmark functions (pure C)
#      cec17.c             ← fitness/error helper
#      cec17.h             ← header
#      cec17_wrapper.c     ← auto-generated glue for Python ctypes
#
#  Files NOT used (ignore them):
#      main.cpp            ← Windows-only example, not needed
#
#  Run once from pso_implementation/ folder:
#      bash build_cec17.sh
# =============================================================

set -e

echo "================================================"
echo "  Building CEC17 shared library for Python"
echo "  (pure C version — no Windows headers)"
echo "================================================"
echo ""

# ── Check required files exist ────────────────────────────────
for f in cec17_test_func.c cec17.c cec17.h; do
    if [ ! -f "$f" ]; then
        echo "[ERROR] $f not found in this folder!"
        echo "        Copy it from your CEC17 folder into pso_implementation/"
        exit 1
    fi
done
echo "[OK] All CEC17 source files found"

# ── Check input_data/ ─────────────────────────────────────────
if [ ! -d "input_data" ]; then
    echo "[WARNING] input_data/ folder not found!"
    echo "          Copy your input_data/ folder here before running pso.py"
    echo ""
else
    COUNT=$(ls input_data/*.txt 2>/dev/null | wc -l)
    echo "[OK] input_data/ found ($COUNT .txt files)"
fi
echo ""

# ── Step 1: Write the C wrapper ──────────────────────────────
echo "[1/2] Writing cec17_wrapper.c..."

cat > cec17_wrapper.c << 'CWRAPPER'
/*
  cec17_wrapper.c — auto-generated by build_cec17.sh
  Do not edit manually.

  PURPOSE:
  The new cec17_test_func.c already declares its globals at the
  top of the file (OShift, M, y, z, x_bound, ini_flag, etc.)
  So this wrapper only needs to expose the clean Python interface.

  Exposes one function to Python via ctypes:
      double cec17_call(double *x, int nx, int func_num)
*/

/* Forward declaration — defined in cec17_test_func.c */
void cec17_test_func(double *x, double *f, int nx, int mx, int func_num);

/* Single-solution wrapper callable from Python */
double cec17_call(double *x, int nx, int func_num) {
    double f = 0.0;
    cec17_test_func(x, &f, nx, 1, func_num);
    return f;
}
CWRAPPER

echo "      cec17_wrapper.c written"
echo ""

# ── Step 2: Compile everything into cec17.so ─────────────────
echo "[2/2] Compiling cec17.so..."
echo "      Sources: cec17_test_func.c  cec17.c  cec17_wrapper.c"

gcc -O2 -shared -fPIC \
    -o cec17.so \
    cec17_wrapper.c \
    cec17_test_func.c \
    cec17.c \
    -lm

echo "      cec17.so compiled successfully"
echo ""

# ── Done ─────────────────────────────────────────────────────
echo "================================================"
echo "  Build complete!"
echo ""
echo "  Next — test the bridge:"
echo "      python cec17_bridge.py"
echo ""
echo "  If that passes, run the full PSO:"
echo "      python pso.py"
echo "================================================"