/*
  cec17_wrapper.c — auto-generated by build_cec17.sh
  Do not edit manually.

  PURPOSE:
  The new cec17_test_func.c already declares its globals at the
  top of the file (OShift, M, y, z, x_bound, ini_flag, etc.)
  So this wrapper only needs to expose the clean Python interface.

  Exposes one function to Python via ctypes:
      double cec17_call(double *x, int nx, int func_num)
*/

/* Forward declaration — defined in cec17_test_func.c */
void cec17_test_func(double *x, double *f, int nx, int mx, int func_num);

/* Single-solution wrapper callable from Python */
double cec17_call(double *x, int nx, int func_num) {
    double f = 0.0;
    cec17_test_func(x, &f, nx, 1, func_num);
    return f;
}
